kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: alinbalutoiu/argocd
    tags: arm
    build_args:
      - BUILD_DARWIN_CLI="false"
      - BUILD_WINDOWS_CLI="false"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
