kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: alinbalutoiu/argocd
    tags: arm
    build_args:
      - BUILD_ALL_CLIS="false"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: alinbalutoiu/argocd
    tags: arm64
    build_args:
      - BUILD_ALL_CLIS="false"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
